apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec: 
  containers:
    - name: nginx
      image: nginx
      envFrom: # this is used to refer all the values in daws-78 in a single go
        - configMapRef:
            name: daws-78 
      # env:
      # - name: course
      #   valueFrom:
      #     configMapKeyRef:
      #       name: daws-78
      #       key: course
      # - name: trainer
      #   valueFrom:
      #     configMapKeyRef:
      #       name: daws-78
      #       key: trainer
            

              
            
