apiVersion: v1
kind: Pod
metadata:
  name: pod-config
spec: 
  containers:
    - name: nginx
      image: nginx
      env:
      - name: course
        valueFrom:
          configMapKeyRef:
            name: daws-78
            key: course
      - name: trainer
        valueFrom:
          configMapKeyRef:
            name: daws-78
            key: trainer
      

              
            
